doc: add some research on the overhead of cd

diff --git a/research/test-directories/run-tests b/research/test-directories/run-tests
--- a/research/test-directories/run-tests
+++ b/research/test-directories/run-tests
@@ -84,6 +84,10 @@ fi
 # Store the path to the run-tests.sh script for later use
 tsk_orig_cwd="$(pwd)"     # save the directory we were started in
 tsk_framework_file="$(readlink -f "${BASH_SOURCE[0]}")"
+tsk_repeat=1              # the number of times to repeat the entire test run
+
+# if config files exclude any directories, they're stored here until argumets are processed
+tsk_excluded_dirs=()
 
 # if the user ran a testfile directly (`./01.test`), tsk_launched_file will be that file
 tsk_launched_file=""
@@ -91,14 +95,11 @@ if [ "${BASH_SOURCE[0]}" != "$0" ]; then
     tsk_launched_file="${BASH_SOURCE[1]}"
 fi
 
-# tests have their output redirected to files so we need to:
-exec 3>&1 4>&2 # save stdout and stderr to FDs 3 and 4
-
 # TODO: this is a misnomer... we also use tsk_use_color to indicate
 # if we should use control codes to do curses-style terminal output
 if [ -z "${tsk_use_color}" ]; then
     tsk_use_color=false
-    if [ -t 3 ]; then
+    if [ -t 1 ]; then
         tsk_use_color=true
     fi
 fi
@@ -118,6 +119,14 @@ else
     NC=''
     CR=''
 fi
+
+# Benchmark timing variables
+tsk_benchmark_enabled=false
+tsk_benchmark_start_time=""
+tsk_benchmark_total_time=0
+
+# tests have their output redirected to files so we need to:
+exec 3>&1 4>&2 # save stdout and stderr to FDs 3 and 4
 
 
 #
@@ -290,35 +299,61 @@ pluralize() {
     fi
 }
 
+# Prevents the given directories from automatically being included in test runs.
+# (excluded tests can still be run by naming them explicitly on the command line)
+exclude_directory() {
+    case "$1" in
+        *[\*\?\[\]\\]*) abort "invalid filename: '$excluded_dir'" ;;
+    esac
+    tsk_excluded_dirs+=("$1")
+}
+
 
 #
 #    Internal code to run the tests
 #
 
-# accepts testfiles and directories
-_add_argument() {
-    if [ -d "$1" ]; then
-        while IFS= read -r file; do
-            testfiles+=("$file")
-        done < <(find "$1" -type f \( -name "*.test" -o -name "*.skip" \) | sort)
-    else
-        testfiles+=("$1")
+_expand_directory() {
+    local find_args=("$1")
+    local excluded_dir
+
+    # prune any excluded directories
+    for excluded_dir in "${tsk_excluded_dirs[@]}"; do
+        find_args+=("-path" "*/$excluded_dir" "-prune" "-o")
+    done
+    # match .test and .skip files
+    find_args+=("-type" "f" "(" "-name" "*.test" "-o" "-name" "*.skip" ")" "-print0")
+    # run find, sort it, and stuff its results into the testfiles array
+    while IFS= read -r -d '' testfile; do
+        testfiles+=("$testfile")
+    done < <(find "${find_args[@]}" | sort -z)
+}
+
+# also ensures the number is positive
+_ensure_numeric_argument() {
+    if ! [[ "$2" =~ ^[0-9]+$ ]]; then
+        echo "invalid $1 argument: $2" >&2
+        exit 1
     fi
 }
 
 _process_arguments() {
-    testfiles=()
+    local arguments=()
+    testfiles=() # TODO: declare this global list of testfiles
     max_jobs=12  # not the fastest but should be reasonably close
 
     # If the test harness is being sourced from a testfile, add the testfile.
     if [ -n "$tsk_launched_file" ]; then
-        testfiles+=("$tsk_launched_file")
+        arguments+=("$tsk_launched_file")
     fi
 
     # TODO: if a directory is specified, add all .test files in that directory
     # TODO: should we care about whether a testfile argument ends in '.test'?
     while (( "$#" )); do case $1 in
+        -b|--benchmark) tsk_benchmark_enabled=true; shift;;
         -d|--diff) tsk_use_diff=true; shift;;
+        -e|--exclude) exclude_directory "$2"; shift; shift;;
+        --exclude=*) exclude_directory "${1#*=}"; shift;;
         -f|--formatter) tsk_test_formatter="$2"; shift; shift;;
         --formatter=*) tsk_test_formatter="${1#*=}"; shift;;
         -j|--jobs) max_jobs="$2"; shift; shift;;
@@ -326,20 +361,30 @@ _process_arguments() {
         -k|--keep) tsk_keep_artifacts=true; shift;;
         -m|--matching) tsk_match_utility="grep $2"; shift; shift;;
         --matching=*) tsk_match_utility="grep ${1#*=}"; shift;;
+        -r|--repeat) tsk_repeat="$2"; shift; shift;;
+        --repeat=*) tsk_repeat="${1#*=}"; shift;;
         -w|--watch) WATCH=true; shift;;               # TODO
-        *) _add_argument "$1"; shift;;
+        *) arguments+=("$1"); shift;;
     esac; done
 
-    # ensure max_jobs is a positive integer
-    if [[ ! "$max_jobs" =~ ^[0-9]+$ ]]; then
-        echo "invalid max jobs: '$max_jobs'"
-        exit 1
+    _ensure_numeric_argument "max jobs" "$max_jobs"
+    _ensure_numeric_argument "repeat" "$tsk_repeat"
+
+    # If no files or directories were specified, run all files in the cwd.
+    if [ ${#arguments[@]} -eq 0 ]; then
+        arguments+=(".")
     fi
 
-    # If no test files were specified, run all .test files recursively
-    if [ ${#testfiles[@]} -eq 0 ]; then
-        _add_argument '.'
-    fi
+    # expand the arguments into an array of testfiles
+    for arg in "${arguments[@]}"; do
+        if [ -d "$arg" ]; then
+            _expand_directory "$arg"
+        elif [ -f "$arg" ]; then
+            testfiles+=("$arg")
+        else
+            abort "Could not find $arg"
+        fi
+    done
 
     if [ ${#testfiles[@]} -eq 0 ]; then
         echo "No testfiles found. Testfile names must end in '.test'." >&2
@@ -591,11 +636,11 @@ _compute_test_result() {
 _run_testfile_tests() {
     local tsk_testfile="$1"
 
+    # in case the user named a ".skip" file on the command line
     tsk_skip_all_tests=""
     if [[ "$tsk_testfile" == *.skip ]]; then
         tsk_skip_all_tests=true
     fi
-
 
     # load the testfile if it's not already loaded
     if [ "$tsk_testfile" != "$tsk_launched_file" ]; then
@@ -668,7 +713,7 @@ _prepare_test_environment() {
 
     tsk_keep_artifacts=''
     tsk_use_diff=''
-    tsk_match_utility='cat'
+    tsk_match_utility='cat' # TODO: accepting code from user: make sure this isn't a vuln!
 
     # TODO: running in /tmp isn't good for tests that require giant files
     # TODO: option to create and mount a ramdisk to run tests
@@ -680,6 +725,9 @@ _prepare_test_environment() {
     else
         tsk_root_dir="$(mktemp -d "/tmp/bashtest-XXXXXX")"
     fi
+
+    local config_file="$(dirname "$tsk_framework_file")/test-config.sh"
+    [ -f "$config_file" ] && source "$config_file"
 }
 
 # given a testfile, ensure we return a unique name for this test
@@ -718,25 +766,52 @@ _run_multiple_testfiles() {
     wait  # wait for the remaining jobs to finish
 }
 
-# there are many ways to run the tests:
-# - Run multiple test files: ./run-tests file1.test file2.test
-# - Run a single test file: ./01-my-tests.test
-# - You should also be able to run multiple tests: ./01-a.test 02-b.test
-# - if you name a directory, all tests in that directory will be run.
-# - if you don't name any directories or files, the cwd will be searched for tests.
+_run_tests() {
+    if [ "$tsk_benchmark_enabled" = true ]; then
+        tsk_benchmark_start_time=$(date +%s%N)  # epoch seconds + nanoseconds
+    fi
+
+    # if the user supplies a single testfile, we show a more verbose output than if they're running multiple
+    if [ ${#testfiles[@]} -eq 1 ]; then
+        tsk_test_formatter="${tsk_test_formatter:-list}"
+        _run_testfile_tests "${testfiles[0]}"
+    else
+        # TODO: need to print failures and results when running multiple test files
+        tsk_test_formatter="${tsk_test_formatter:-dot}"
+        _run_multiple_testfiles
+    fi
+
+    _${tsk_test_formatter}_formatter_test_summary
+
+    if [ "$tsk_benchmark_enabled" = true ] && [ -n "$tsk_benchmark_total_time" ]; then
+        elapsed_ms=$(( ($(date +%s%N) - tsk_benchmark_start_time) / 1000000 ))
+        tsk_benchmark_total_time=$(printf "%d.%03d" $((elapsed_ms / 1000)) $((elapsed_ms % 1000)))
+        echo -e "${GREEN}Running${NC} ${#testfiles[@]} ${GREEN}$(pluralize ${#testfiles[@]} testfile) took${NC} ${tsk_benchmark_total_time} ${GREEN}seconds${NC}"
+    fi
+}
+
+# TODO: if we're benchmarking, can we summarize the results?
+_repeat_tests() {
+    # If tsk_repeat is not set or is empty, run tests once
+    if [ -z "$tsk_repeat" ]; then
+        tsk_repeat=1
+    fi
+
+    while [ "$tsk_repeat" -gt 0 ]; do
+        ( _run_tests )
+        local exit_code="$?"
+        if [ "$exit_code" -ne 0 ]; then
+            exit "$exit_code"
+        fi
+        tsk_repeat=$((tsk_repeat - 1))
+    done
+}
 
 _prepare_test_environment
 _process_arguments "$@"
-# if the user supplies a single testfile, we show a more verbose output than if they're running multiple
-if [ ${#testfiles[@]} -eq 1 ]; then
-    tsk_test_formatter="${tsk_test_formatter:-list}"
-    _run_testfile_tests "${testfiles[0]}"
-else
-    # TODO: need to print failures and results when running multiple test files
-    tsk_test_formatter="${tsk_test_formatter:-dot}"
-    _run_multiple_testfiles
-fi
-_${tsk_test_formatter}_formatter_test_summary
+_repeat_tests
+
+# Clean up if not in watch mode and not keeping artifacts
 if [ "$tsk_keep_artifacts" != true ]; then
     rm -rf "$tsk_root_dir"
 fi
